import { Router } from "express";
import { authRoutes } from "./auth/auth.routes.js";
import { adminRoutes } from "./admin/admin.routes.js";
import { eventsRoutes } from "./events/events.routes.js";
import { vendorsRoutes } from "./vendors/vendors.routes.js";
import { bookingsRoutes } from "./bookings/bookings.routes.js";
import { packagesRoutes } from "./packages/packages.routes.js";
import { locationsRoutes } from "./locations/locations.routes.js";
import { categoriesRoutes } from "./categories/categories.routes.js";
import { vendorBookingsRoutes } from "./bookings/vendor-bookings.routes.js";
import { verificationRequestsRoutes } from "./verification-requests/verification-requests.routes.js";
import { adminVerificationRequestsRoutes } from "./verification-requests/admin-verification-requests.routes.js";
import { documentsRoutes } from "./documents/documents.routes.js";
import { availabilityRoutes } from "./availability/availability.routes.js";
import { vendorQuotesRoutes } from "./quotes/vendor-quotes.routes.js";
import { quotesRoutes } from "./quotes/quotes.routes.js";
import { paymentsRoutes } from "./payments/payments.routes.js";
import { refundsRoutes } from "./payments/refunds.routes.js";
import { vendorPaymentsRoutes } from "./payments/vendor-payments.routes.js";
import { conversationsRoutes } from "./conversations/conversations.routes.js";
import { notificationsRoutes } from "./notifications/notifications.routes.js";
import { reviewsRoutes } from "./reviews/reviews.routes.js";
import { vendorReviewsRoutes } from "./reviews/vendor-reviews.routes.js";
import { favoritesRoutes } from "./favorites/favorites.routes.js";
import { supportTicketsRoutes } from "./support-tickets/support-tickets.routes.js";
import { adminSupportTicketsRoutes } from "./support-tickets/admin-support-tickets.routes.js";
import { reportsRoutes } from "./reports/reports.routes.js";
import { adminReportsRoutes } from "./reports/admin-reports.routes.js";
import { auditLogsRoutes } from "./audit-logs/audit-logs.routes.js";
import { accountRoutes } from "./account/account.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRoutes);
apiRouter.use("/admin", adminRoutes);
apiRouter.use("/admin", adminVerificationRequestsRoutes);
apiRouter.use("/admin", adminSupportTicketsRoutes);
apiRouter.use("/admin", adminReportsRoutes);
apiRouter.use("/admin", auditLogsRoutes);
apiRouter.use("/events", eventsRoutes);
apiRouter.use("/vendors", vendorsRoutes);
apiRouter.use("/vendors", packagesRoutes);
apiRouter.use("/vendors", verificationRequestsRoutes);
apiRouter.use("/vendors", documentsRoutes);
apiRouter.use("/vendors", availabilityRoutes);
apiRouter.use("/bookings", bookingsRoutes);
apiRouter.use("/locations", locationsRoutes);
apiRouter.use("/categories", categoriesRoutes);
apiRouter.use("/vendors", vendorBookingsRoutes);
apiRouter.use("/vendors", vendorQuotesRoutes);
apiRouter.use("/vendors", vendorReviewsRoutes);
apiRouter.use("/vendors", vendorPaymentsRoutes);
apiRouter.use("/quotes", quotesRoutes);
apiRouter.use("/payments", paymentsRoutes);
apiRouter.use("/refunds", refundsRoutes);
apiRouter.use("/conversations", conversationsRoutes);
apiRouter.use("/notifications", notificationsRoutes);
apiRouter.use("/reviews", reviewsRoutes);
apiRouter.use("/favorites", favoritesRoutes);
apiRouter.use("/support-tickets", supportTicketsRoutes);
apiRouter.use("/reports", reportsRoutes);
apiRouter.use("/account", accountRoutes);
